# Generated by Django 5.2.14 on 2026-05-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_round_trip_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='flightoffer',
            new_name='flights_fli_origin_b22c03_idx',
            old_name='flights_fli_origin_92dac1_idx',
        ),
        migrations.RenameIndex(
            model_name='flightsearch',
            new_name='flights_fli_origin_f01ddf_idx',
            old_name='flights_fli_origin_d402f6_idx',
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='provider_link_status',
            field=models.CharField(choices=[('exact', 'Exact provider offer link'), ('search_page', 'Provider search page fallback'), ('session_required', 'Provider session required'), ('unavailable', 'Unavailable')], db_index=True, default='unavailable', max_length=32),
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='provider_offer_key',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='provider_offer_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='provider_search_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
